(clear)
(reset)
(unwatch instances)
(load "00_allthetemplate.clp")
(load "01_a_timetabletemplate.clp")
(load "ModuleTime_Fact.clp")
(load "ModuleExam_Fact.clp")
(load "ModuleInformation_Fact.clp")
(load "ModulePreclude_Fact.clp")
(load "ModulePrereq_Fact.clp")
(load "ModuleTag_Fact.clp")
(load "timetable.clp")
(load "prereq.clp")
(reset)
(watch instances)
