(clear)
(reset)
(unwatch instances)
(unwatch rules)
(load C:/Users/User/Documents/GitHub/CS4244/00_allthetemplate.clp)
(load C:/Users/User/Documents/GitHub/CS4244/01_a_timetabletemplate.clp)
(load C:/Users/User/Documents/GitHub/CS4244/01_Initialize.clp)
(load C:/Users/User/Documents/GitHub/CS4244/01_b_cleaning.clp)
(load C:/Users/User/Documents/GitHub/CS4244/02_ModuleSelection.clp)
(load C:/Users/User/Documents/GitHub/CS4244/03_ModulePrereqSelect.clp)
(load C:/Users/User/Documents/GitHub/CS4244/04_ModulePreclusion.clp)
(load C:/Users/User/Documents/GitHub/CS4244/05_ModuleSelection.clp)
(load C:/Users/User/Documents/GitHub/CS4244/ModuleInformation_Fact.clp)
(load C:/Users/User/Documents/GitHub/CS4244/ModuleTag_Fact.clp)
(load C:/Users/User/Documents/GitHub/CS4244/ModulePrereq_Fact.clp)
(load C:/Users/User/Documents/GitHub/CS4244/ModulePreclude_Fact.clp)
(load C:/Users/User/Documents/GitHub/CS4244/ModuleTime_Fact.clp)
(load C:/Users/User/Documents/GitHub/CS4244/ModuleExam_Fact.clp)

(load C:/Users/User/Documents/GitHub/CS4244/timetable.clp)

(load "99_testcase1.txt")
(reset)
(focus INITIALIZE)
(run)
(focus CLEANING)
(run)
(focus MODULESELECTION)
(run)

