(clear)
(reset)
(unwatch instances)
(unwatch rules)
(load "00_allthetemplate.clp")
(load "01_a_timetabletemplate.clp")
(load "01_Initialize.clp")
(load "01_Initialize_2.clp")
(load "01_b_cleaning.clp")
(load "02_ModuleSelection.clp")
(load "prereq.clp")
(load "03_ModulePrereqSelect.clp")
(load "04_ModulePreclusion.clp")
(load "05_ModuleSelection.clp")
(load "05_ModuleSelection_2.clp")
(load "ModuleInformation_Fact.clp")
(load "ModuleTag_Fact.clp")
(load "ModuleExam_Fact.clp")
(load "ModuleTime_Fact.clp")
(load "ModulePrereq_Fact.clp")
(load "ModulePreclude_Fact.clp")
(load "timetable.clp")
(load "input.txt")
(reset)
(focus INITIALIZE)
(run)
(focus AFTERINITIALIZE)
(run)
(focus CLEANING)
(run)
(focus MODULESELECTION)
(run)
(focus TIMETABLE)
(run)
(focus TIMETABLE)
(print-out-url)
